### ISSUE TITLE
Demo2 - Detail Post - Minimap, implement click action

### ISSUE THREAD

**Issue by tinygipxy** [reway/bds#22]

**Comment by tinygipxy** [comment]
Can open loai map result khac, chi bao gom 1 nha

**Comment by ngchibinh** [comment]
Click vào để mở ra một bản đồ trong đó chỉ có duy nhất nhà đang xem.

**Comment by ngchibinh** [comment]
Dev tham khảo ảnh chụp giao diện bản đồ sau khi click vào minimap của app PropertyGury
![img_1725](https://cloud.githubusercontent.com/assets/17264625/15066726/abebd322-1395-11e6-80e2-7f32eea24135.PNG)

**Comment by ngchibinh** [comment]
Có đầy đủ icon oto để sử dụng tính năng dẫn đường và mục satelline để chuẩn đổi map nhé. Màu sắc dùng màu của mình
