### ISSUE TITLE
 Open Demo2 - List result - Thêm icon cho các nút chức năng. Sử dụng bộ icon và quy cách đặt icon giống Carousell

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#33]

**Comment by tinygipxy** [comment]
Gửi mày một số icon trước. Các cái khác chọn tiếp sau khi tham khảo các icon này trên app nhé

I.HOME SCREEN
	1. Home:		Trulia-71.
	2. Inbox:			Fontello/linecons-Inbox
	3. Sell:			Fontello/linecons-Camera
	4. Activity:		Trulia-31???
	5. Me:			Trulia-117
	6. Search:		Trulia-105

II. LIST RESULT
	1. Sort			Font Awesome-Sort
	2. Save serach:	Font Awesome-Hdd-o
	3. Map:			Font Awesome-Map-o

III. DETAIL POST
	1. Phone:		Trulia-15
	2. Chat:			Trulia-41
	3. Save home:	Trulia-69
	4. Back:			Trulia-74
	5. Share:		Apple share icon

**Comment by tinygipxy** [comment]
Chu co icon cho Search screen:
![image](https://cloud.githubusercontent.com/assets/7077139/14407858/61513350-ff0b-11e5-8d6c-89d297921513.png)
