### ISSUE TITLE
Demo2 - Detail Post - Thông tin vắn tắt phía trên tin - Bỏ chữ bán trong loại nhà đi. Thông số được trình bày tuần tự đến khi hết. Thông số cuối cùng là "Tin đăng được x ngày" thay cho ngày đăng tin. 

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#35]

**Comment by ngchibinh** [comment]
Phần thông tin chi tiết do ngươi dùng viết nên để 3 dòng cho dễ phân biệt với các mục khác và cân đối hơn

**Comment by tinygipxy** [comment]
Sua phan extract data

**Comment by ngchibinh** [comment]
Thêm phần giá/m2 vào mục đặc điểm nhé. Quy đổi hết về giá tổng. Cái nào thiếu thông tin diện tích thì quy thành thoả thuận hết. Hiển thị giá tổng thôi.

**Comment by ngchibinh** [comment]
Địa chỉ trong mục đặc điểm nếu quá 4 dòng hiển thị bị thiếu

**Comment by ngchibinh** [comment]
Đường phía trên mục đặc điểm kéo dài ra ngoài để phân chia với mục phía trên. Mục chia sẻ nằm dưới bản đồ. Đường kẻ phía trên bản đồ là kẻ ngắn

**Comment by ngchibinh** [comment]
Commend ngay phía trên commend này bỏ qua nhé
