### ISSUE TITLE
Demo2 - Search Page - Designed Layout-Page 01 - Dùng cho tìm kiếm trong một khu vực địa chính

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#51]
![search-01](https://cloud.githubusercontent.com/assets/17264625/14525066/ff126fa2-0265-11e6-965c-108b8a5cd085.png)

**Comment by tinygipxy** [comment]
No need show/hide, luon luon hien thi nhu vay

**Comment by ngchibinh** [comment]
Không còn nút thu gọn lại sau khi nhấn nút mở rộng. Còn khi người dùng nhấn nút thiết lập lại, mọi thứ quay về ban đầu (Lúc chưa nhấn mở rộng và các giá trị filter là default)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14579256/7e9e490a-03cc-11e6-8fe4-1df5d2da6e73.png)

**Comment by tinygipxy** [comment]
Chu Hanoi tren headerInput, can left-align

**Comment by ngchibinh** [comment]
Nền của mình màu bị hơi xanh chứ ko trắng. 
Chỗ nền ngăn màu xám thì mình hơi hồng. 
Dòng kẻ giữa các mục bị dài. 
Taskbar bên dưới thấp hơn một xíu dẫn đến tổng thể phía trên cũng thấp hơn chút xíu (zoom to sẽ thấy).

**Comment by ngchibinh** [comment]
Nên cho thêm một ảnh đặt theo chiều dọc để dễ so sánh theo phương dọc.

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14579424/06a8c126-03d3-11e6-9772-684be7a9d884.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14579452/f2eebb08-03d3-11e6-92a9-064a221d2303.png)
![image](https://cloud.githubusercontent.com/assets/6780101/14579457/0bb4445a-03d4-11e6-9bb8-8fa116be9532.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14579461/5c4e928a-03d4-11e6-90f3-29dcf9c88629.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14579462/6bd1b354-03d4-11e6-843e-6fc234650de4.png)
![image](https://cloud.githubusercontent.com/assets/6780101/14579464/8064b1ea-03d4-11e6-8f08-9536b284388c.png)

**Comment by ngchibinh** [comment]
Font dùng để chọn số phòng ngủ (nhà tắm) nhỏ hơn design. Kiểm tra lại xem đúng font và kích thước không

**Comment by ngchibinh** [comment]
Taskbar bên dưới đã cao như design. Tuy nhiên các mục trên vẫn thấp hơn một xíu (Tổng thế đến tận search bar). So sánh dựa theo các đường kẻ. Chỉnh lại như đã chỉnh taskbar bên dưới là ok.

**Comment by ngchibinh** [comment]
Thanh màu xanh dưới nút Bán hơi dài. Nó phải thẳng mép trái nút search.

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14580799/14ebc96e-0404-11e6-82b9-59fe80abc42c.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14580811/6cc41498-0404-11e6-8195-b4ab91305535.png)
![image](https://cloud.githubusercontent.com/assets/6780101/14580814/7c311e12-0404-11e6-89d8-718a3b72dcbb.png)

**Comment by hainguyen1981** [comment]
SegmentedControlIOS ko support change fontSize, fontFamily nen text trong cac segment chua thay doi.

**Comment by ngchibinh** [comment]
Chữ "Bất kỳ" ở mục Loại nhà đất ko thẳng hàng với hai chữ bất kỳ kia. Vị trí hai mũi tên quay xuống cũng chưa đúng tke. Dùng cạnh phải của màn hình để căn thẳng hàng giữa ảnh thiết kế và ảnh của giao diện là phát hiện ra ngay.

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14588070/57178e9a-04ea-11e6-9fb9-776c0692b115.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14588074/8d6ba6e8-04ea-11e6-9e46-c36e57bd4814.png)
![image](https://cloud.githubusercontent.com/assets/6780101/14588080/a632553c-04ea-11e6-9b92-968a187732cd.png)

**Comment by ngchibinh** [comment]
Vẫn chưa giải quyết xong phần này nhé dev: "Chữ "Bất kỳ" ở mục Loại nhà đất ko thẳng hàng với hai chữ bất kỳ kia. Vị trí hai mũi tên quay xuống cũng chưa đúng tke. Dùng cạnh phải của màn hình để căn thẳng hàng giữa ảnh thiết kế và ảnh của giao diện là phát hiện ra ngay."

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14588336/46b662f4-04f1-11e6-8bec-cb99b2b135fc.png)

**Comment by ngchibinh** [comment]
Ngon rồi. Còn cái mũi tên nữa nhé. Mũi nhọn nằm cùng một đường thẳng. Lấy mũi nhọn của mũi tên trong Loại Nhà đất làm mốc nhé

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14588412/5a3bafc6-04f3-11e6-9a4f-52c6ecf5001b.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14588430/e59887ec-04f3-11e6-85dd-c1c16cfeda4a.png)

**Comment by ngchibinh** [comment]
Last thing: các ô giá trị và dòng kẻ bên dưới của mục số nhà tắm bị cao hơn thiết kế một xíu

**Comment by ngchibinh** [comment]
Comment ngay phía trên đã fix chưa. Nếu rồi thì upload ảnh để mình review giúp nhé.

**Comment by tinygipxy** [comment]
![image](https://cloud.githubusercontent.com/assets/7077139/14766848/ae6d771c-0a4a-11e6-9100-a77b8a6d1050.png)

**Comment by tinygipxy** [comment]
![image](https://cloud.githubusercontent.com/assets/7077139/14766863/f0059952-0a4a-11e6-9292-587874197b56.png)

**Comment by tinygipxy** [comment]
![image](https://cloud.githubusercontent.com/assets/7077139/14766872/25756e28-0a4b-11e6-8b8f-4c35238c55d2.png)
