### ISSUE TITLE
Demo2 - Search Page - Designed Layout-Page 05 - Dùng cho tìm kiếm xung quanh một địa điểm-Screen này đã sửa lỗi bị lệch Hoài comment -update 06/05/2016

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#52]
![search-05](https://cloud.githubusercontent.com/assets/17264625/15063758/c417aad0-1376-11e6-9563-5f0202ca9ab2.png)

**Comment by tinygipxy** [comment]
Ban kinh, chuyen thanh: 0.5, 1, 2,3,4,5

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14584531/9aca6b10-0474-11e6-87f5-c74e332b8096.png)

**Comment by ngchibinh** [comment]
Các chữ bất kỳ đã thẳng hàng nhưng cần dịch sang phải chút xíu nữa (Mép trái chữ B thẳng với mép phải chữ H trong chữ Thực hiện bên dưới). Các mũi tên quay xuống cần dịch sang phải chút xíu sao cho mũi nhọn của nó thẳng hàng với mũi nhọn của mũi tên quay ngang.

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14593165/34f89ad6-0551-11e6-956e-f160e066b3ae.png)

**Comment by ngchibinh** [comment]
Screen ban đầu do thiết kế làm bị phát hiện hơi lệch. Team dev kiểm tra giao diện code đã match theo screen mới chưa.

**Comment by tinygipxy** [comment]
![image](https://cloud.githubusercontent.com/assets/7077139/14761668/e289b41c-099a-11e6-943c-7a6821e23662.png)
Ben trai la` DEV, ben phai la` DESIGN nhe'

**Comment by ngchibinh** [comment]
Bị lệch nhiều so với design

**Comment by tinygipxy** [comment]
Quen thieu comment, cai nay, design bi lenh, chu DEV chuan

**Comment by ngchibinh** [comment]
Vậy cho một cái ảnh dev chuẩn và design chuẩn để cạnh nhau để so sánh nhé.

**Comment by ngchibinh** [comment]
Vừa update lại design sau khi đã fix lỗi sai chiều cao mục "Bán kính tìm kiếm". Dev kiểm tra kết quả với design để đảm bảo giống như thiết kế.
