### ISSUE TITLE
Demo2 - Search Page - Designed Layout-Page 07 - Dùng cho mục chọn hướng nhà

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#54]
![search-07](https://cloud.githubusercontent.com/assets/17264625/14556930/e2662762-0324-11e6-8bfd-04d2d951c8d3.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14603516/5fad414a-0598-11e6-9c21-ab72f444c1f0.png)

**Comment by tinygipxy** [comment]
Click chon quay ve man hinh trc luon, bo action bar ben duoi

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14761809/96f38e34-0994-11e6-9516-567b3e989b32.png)
