### ISSUE TITLE
Demo2 - Search Page - Designed Layout-Page 04 - Dùng cho mục chọn loại nhà đất

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#55]
![search-04](https://cloud.githubusercontent.com/assets/17264625/14557018/4a1d4c78-0325-11e6-8852-aca6fac34f88.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14589232/39312c84-0507-11e6-85a5-7339c85bdd4d.png)

**Comment by hainguyen1981** [comment]
Cac dong ke cua image design ko deu nhau, nen ko the can cho thang hang duoc.

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14589375/9701b506-050a-11e6-83c5-7fafac74c489.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14603585/d33ac02e-0598-11e6-9d3a-ce717e15082d.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14603601/ee2c01ae-0598-11e6-805e-5427d983b09d.png)
![image](https://cloud.githubusercontent.com/assets/6780101/14603609/fa3a566c-0598-11e6-839a-0e485749ff42.png)

**Comment by ngchibinh** [comment]
Chú ý làm giống screen đã đưa. Dev bỏ chữ tìm kiếm đi.

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14761801/6b0256b6-0994-11e6-93b9-11e6d54f8f9f.png)
