### ISSUE TITLE
Demo2 - Search Page - Designed Layout-Page 06 - Sau khi click vào nút more (Có thêm hướng nhà và ngày đăng). Đã bổ xung phần reset filter. Đây là bản final rồi

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#56]
![search-06](https://cloud.githubusercontent.com/assets/17264625/14666894/433304c2-0706-11e6-911d-5195da9f8ea5.png)

**Comment by tinygipxy** [comment]
Ngay dang: Bat ky, 1,7,14,30, 90. Su dung iosPicker

**Comment by tinygipxy** [comment]
![image](https://cloud.githubusercontent.com/assets/7077139/14563608/61297f42-0355-11e6-9807-09d3f4ca9d31.png)

**Comment by ngchibinh** [comment]
Mặc định là "Bất kỳ" nhé.

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14603722/9ea31766-0599-11e6-8ef3-17285242f5f0.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14641538/f2375b30-0670-11e6-8516-c57f5d8cd5d6.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14641836/47b11d8e-0672-11e6-8897-e3bc54c273b7.png)

**Comment by tinygipxy** [comment]
Click vao "Thiet lap lai"  chua hide muc "Mo rong"
