### ISSUE TITLE
Demo2 - Search Page - Detail Post - Giữ nguyên bố cục tin đăng của người dùng bên bds

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#57]

**Comment by ngchibinh** [comment]
Bố cục nghĩa là nó xuống dòng mình cũng xuống dòng

**Comment by tinygipxy** [comment]
ngon roi, de support them tinh nagn xuong dong

**Comment by tinygipxy** [comment]
http://stackoverflow.com/questions/32469570/how-can-i-insert-new-line-r-n-in-react-native-text-component

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14821857/8b3ca698-0bf6-11e6-8ec0-d5762d51cd00.png)

**Comment by tinygipxy** [comment]
Can ktra lai phan lay du lieu tu bds.com
