### ISSUE TITLE
Demo2 - Search Page - Designed Layout-Page 08 - Dùng cho mục Auto Suggestion khi click vào nút search

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#58]
![search-08](https://cloud.githubusercontent.com/assets/17264625/14667031/17600ace-0707-11e6-9c5b-63e3a417f410.png)

**Comment by ngchibinh** [comment]
Suggestion của mình sẽ có 5 dòng chứ không phải 3 dòng như thiết kế. Phần icon bên tay trái sẽ bổ xung sau

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/15086705/cb837f9c-140c-11e6-8c1c-19fc751a9ebc.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/15087796/85b26898-1416-11e6-808c-bc14870cd902.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/15087858/41d977c8-1417-11e6-9243-74ab00d61622.png)
