### ISSUE TITLE
Demo2 - List Result Page - Designed Layout-Page 01 - Dùng cho mục hiển thị list result

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#59]
![list-01](https://cloud.githubusercontent.com/assets/17264625/14667105/a8eefefa-0707-11e6-800e-c31473e3347e.PNG)

**Comment by tinygipxy** [comment]
Can them mo ta chi tiet cho thong tin ve Gia, ...

**Comment by ngchibinh** [comment]
Có 3 thông tin hiển thị trên ảnh:
1. Giá: Quy thành đơn vị Tỷ
2. Địa chỉ
3. Diện tích

**Comment by tinygipxy** [comment]
Gia': voi Nha` BAN la` TY, voi nha` THUE la` Trieu/thang

**Comment by ngchibinh** [comment]
Bổ xung thêmthông số thứ 4 là Phòng Ngủ. Hiển thị dạng như sau "Dự án Time City ... 68m²-2PN"

**Comment by ngchibinh** [comment]
"Dự án Time City ... 68m²-2pn"

**Comment by ngchibinh** [comment]
Tuy theo loại bds chọn thông số hiển thị phù hợp ngoài giá và địa chỉ:
- Chung cư: Diện tích + Phòng Ngủ
- Nhà riêng: Diện tích + Số tầng
- Nhà mặt phố: Diện tích + Số tầng
- Biệt thự liền kề: Diện tích + Số tầng
- Đất: Diện tích
- Bds khác: Diện Tích

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14766944/43ad3d1e-0a44-11e6-9f59-66b1a4f86974.png)

**Comment by tinygipxy** [comment]
Van co' loi, vuot vao image cuoi cung, thi` bi chuyen qua Detail Screen

**Comment by ngchibinh** [comment]
Vuốt vào image đầu tiên 2 lần cũng bị vào detail

**Comment by ngchibinh** [comment]
Image đầu và cuối cần có hiệu ứng để người dùng biết. Sử dụng hiệu ứng giống tin đầu tiên của list view khi kéo xuống sẽ nhìn thấy nền màu trắng phía dưới

**Comment by tinygipxy** [comment]
Create separate issue for this bug to make it clear
