### ISSUE TITLE
Demo2 - List Result Page - Designed Layout-Page 02 - Dùng cho mục hiển thị menu sắp xếp trong list result 

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#60]
![list-02](https://cloud.githubusercontent.com/assets/17264625/14667140/d7758884-0707-11e6-9b0e-600114cde8a1.PNG)

**Comment by ngchibinh** [comment]
Các lựa chọn trong mục sắp xếp có chút thay đổi như sau:

Đối với tìm kiếm trong một khu vực địa chính:
1. Mặc định
2. Ngày đăng
3. Giá (Tăng dần)
4. Giá (Giảm dần)
5. Giá/m2
6. Số phòng ngủ
7. Diện tích

Đối với tìm kiếm Xung quanh một địa điểm:
1. Mặc định
2. Ngày đăng
3. Giá (Tăng dần)
4. Giá (Giảm dần)
5. Giá/m2
6. Số phòng ngủ
7. Khoảng cách
8. Diện tích

**Comment by tinygipxy** [comment]
Giong voi Trulia, click 2 lan, thi` sort giam dan cho : SoPhongNgu, DienTich, KhoangCach

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14763613/c6da229a-09c4-11e6-838e-e4f81e555680.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14766857/6c60048c-0a42-11e6-8153-e7c1250d66e3.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14766869/acb5e77c-0a42-11e6-9680-90fea09cd95c.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14768449/ab0575f8-0a6c-11e6-842d-e624ed9bc5d9.png)
