### ISSUE TITLE
Demo2 - List Result Page - Designed Layout-Page 03 - Dùng cho mục hiển thị manu khi nhấn vào save search

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#61]
![list-03](https://cloud.githubusercontent.com/assets/17264625/14667176/0cd3b06e-0708-11e6-9ea1-8a25bc291d6c.PNG)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14761114/056dbccc-0981-11e6-92e0-1e61546e50f4.png)

**Comment by tinygipxy** [comment]
Cho tinh nang qly user
