### ISSUE TITLE
Demo2 - Detail Post - Designed Layout-Page 01 - Dùng cho mục hiện thị chi tiết tin đăng

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#63]
![detail-2](https://cloud.githubusercontent.com/assets/17264625/14738719/65fe6a52-08ad-11e6-9ae4-dd7cc8335643.PNG)

**Comment by tinygipxy** [comment]
1. Khi moi mo screen nay, tat ca cac muc se o trang thai open nhu hinh tren ?
2. Muc vi tri' (minimap), gio thuoc phan "Dac Diem", tuc la close/open theo DacDiem ?
3. TInh nang DanDuong da lam bao gio chua ?
4. Title "Chi Tiet" co can thiet ko ?

**Comment by ngchibinh** [comment]
1. Thông tin của mình ít hơn trulia, do đó mình để open hết. Tổng cũng chỉ tầm 2.5 trang màn hình thôi. 

2. Minimap thuộc phần đặc điểm luôn. Close/open theo phần đặc điểm

3. Tính năng dẫn đường giúp người dùng khi muốn đi xem nhà có thể biết đường đi luôn chứ ko phải soi trên bản đồ hoặc hỏi đường (Tham khảo nhiều người thấy phản hồi positive với tính năng này). 
Tính năng này hoàn toàn dùng google map giống Trulia. Khi click vào nó sẽ chuyển qua google map để dẫn đường luôn nên tao đoán sẽ ko tốn nhiều resource cho nó (Nếu thực tế tốn nhiều resource thì anh em dev báo lại để cả team cân nhắc)

4. Title "Chi tiết" được đưa vào để giúp giao diện đẹp hơn mà thôi. Ko có giá trị nào khác.

**Comment by tinygipxy** [comment]
Ref: http://stackoverflow.com/questions/31535582/get-directions-api-call-react-native

**Comment by tinygipxy** [comment]
Bo thong tin "Khoang Cach Tim Kiem"

**Comment by tinygipxy** [comment]
![image](https://cloud.githubusercontent.com/assets/7077139/14888174/887adc7c-0d8b-11e6-83ae-954cd2e9af05.png)
Nhieu gia' bi khong du khoang cach, bi xuong dong?

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14929605/86a6bef4-0e88-11e6-9d35-e8afd7a1af98.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14929612/94fa67ee-0e88-11e6-896e-28722d506d3b.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14929670/de1e45bc-0e88-11e6-8524-2402f8e52c28.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14929690/f3cf3768-0e88-11e6-875e-567c9b7e1648.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/14929708/09d04dae-0e89-11e6-9f8e-1c836d82009b.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/15029357/5c7777fc-1277-11e6-823f-94f441a8d5a8.png)
![image](https://cloud.githubusercontent.com/assets/6780101/15029366/6839f678-1277-11e6-9862-5c0df868b49c.png)
![image](https://cloud.githubusercontent.com/assets/6780101/15029369/6db9df0a-1277-11e6-99bb-a307a4d7031b.png)

**Comment by tinygipxy** [comment]
1. Zalo icon bi vo hinh
2. Background can chuyen sang mau WHITE theo design

**Comment by ngchibinh** [comment]
Thêm mục "Copy link" trong share tool.

**Comment by ngchibinh** [comment]
Nút dẫn đường click vào nhiều khi không respond mấy. Chỉnh để dù click vào bất cứ đâu trong cả dòng "Dẫn đường" thì đều chuyển qua map luôn.

**Comment by ngchibinh** [comment]
Mục Môi giới hiện tại chưa có rating nên ko để ngôi sao được. Thay vào đó là thông tin một căn nhà tương tự (Cùng khu vực, loại nhà, mức gía. Cái này sẽ định nghĩa sau) để thu hút người mua gọi điện cho môi giới. Thông tin gồm: Địa chỉ, Diện tích, Giá và số tầng (Giống thông tin vắn tắt ở List result)
