### ISSUE TITLE
Posting Screen-Desinged Layout-Page 01- Giao diện short form để đăng tin sau khi đã chụp ảnh xong

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#67]
![posting-page 01](https://cloud.githubusercontent.com/assets/17264625/15039187/fd9375e8-12d4-11e6-8ac0-93ce8ed3fa7f.PNG)

**Comment by ngchibinh** [comment]
Mục VỊ TRÍ đảo lại thứ tự:
1. Địa chỉ
2. Bản đồ
3. Dự án
4. Hướng nhà

Mục đích là sau khi người dùng nhập địa chỉ, thông tin về Dự án sẽ tự động short list thành các dự án thuộc khu vực Quận đó.

**Comment by tinygipxy** [comment]
Thay đổi chút:
1. Bản đồ trước Vị Trí
2. Khi chon vị trí trên bản đồ, ngoài thông tin về MAP location (lat,lon), hệ thống sẽ tự động lấy Xa, Huyen, Tinh
3. Địa chỉ là chi tiết địa chỉ: Số nhà AAA, ngõ BBB, đường CCC
4. Đự án sẽ giới hạn theo Quận khi chọn vị trí trên MAP

**Comment by tinygipxy** [comment]
Mục ảnh: 4 ảnh giống Carousell

**Comment by tinygipxy** [comment]
![img_2060](https://cloud.githubusercontent.com/assets/7077139/16233082/a898653a-37ff-11e6-936c-0d1228726ea4.PNG)

**Comment by tinygipxy** [comment]
Thông tin nào là bắt buộc ?

**Comment by ngchibinh** [comment]
- Các thông tin không bắt buộc: Hướng nhà, dự án, liên hệ (Do tự lấy từ thông tin acc rồi), chi tiết
- Sau khi đăng tin thành công thì mở màn hình Quản lý tin để người dùng có thể: Sửa, Xoá, Upgrade tin.

**Comment by ngchibinh** [comment]
Short form nên bỏ hai trường Hướng nhà và Dự án

**Comment by tinygipxy** [comment]
Màn hình nhập chi tiết sẽ học theo như vậy:
Có thông tin placeholder để hướng dẫn... không cần làm mục (1) bên dưới
![image](https://cloud.githubusercontent.com/assets/7077139/16290386/7532bdc2-392f-11e6-9538-428c2f5e29a3.png)

**Comment by tinygipxy** [comment]
Bỏ thêm cả thuộc tính "Liên Hệ" trong short form này
