### ISSUE TITLE
Map screen - Gioi han so tin hien thi

### ISSUE THREAD

**Issue by tinygipxy** [reway/bds#70]
![img_1736](https://cloud.githubusercontent.com/assets/7077139/15090327/44b26a1e-1457-11e6-9c03-db827f64dc93.PNG)

**Comment by tinygipxy** [comment]
Gioi han 25 tin, va hien thi giong voi app BDS nhu ben tren: "Đang hiển thị 25 bất động sản trên tổng số 100", "Đang hiển thị 21 bất động sản trên tổng sổ 21"

**Comment by ngchibinh** [comment]
"Đang hiển thị 25 tin trong tổng số 100 tin. Zoom để xem thêm"
