### ISSUE TITLE
Register screen - Designed layout - Page 02 - Dùng để xác minh số điện thoại sau khi user nhập vào để đăng ký

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#83]
![register-02](https://cloud.githubusercontent.com/assets/17264625/15244773/01e6cbe6-192d-11e6-9be3-e3696694d1b9.PNG)
ký

**Comment by tinygipxy** [comment]
Nut "Gui lai" se lam sau, hien thien bo khung truoc
