### ISSUE TITLE
Detail Post - Title Giá/m2 : 1.48 Tỷ

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds#87]
Phần hiển thị Title Giá/m2 không phù hợp với 1.48 Tỷ. 
Cần sửa lại Title của mục giá theo các trường hợp sau 
  - Giá/m2 : 24 Triệu/m2
  - Giá: 1.48 Tỷ
  - Giá: Thỏa thuận  

![image](https://cloud.githubusercontent.com/assets/6210499/15272058/cea33f74-1a91-11e6-839e-8ff930a168fb.png)

**Comment by tinygipxy** [comment]
Can lam giong design voi 2 fields, gia' va gia' /m2:

![image](https://cloud.githubusercontent.com/assets/7077139/15384846/142c740c-1dd0-11e6-91ad-f4b9ae9b4ee8.png)

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/15486087/4b416934-216d-11e6-9231-8b9fcdc413bf.png)
