### ISSUE TITLE
Post Ads - Cai dat tinh nang chup anh khi bat dau dang tin

### ISSUE THREAD

**Issue by tinygipxy** [reway/bds#90]
- Thay tam muc "Activity" thanh "Dang tin" de chay
- Lam giong Carousell, chap anh tu camera

**Comment by hainguyen1981** [comment]
![image](https://cloud.githubusercontent.com/assets/6780101/16389477/5802a798-3cc8-11e6-8c41-fbbff3793ad5.png)
![image](https://cloud.githubusercontent.com/assets/6780101/16389493/67c534e8-3cc8-11e6-890d-d93102e152bd.png)
![image](https://cloud.githubusercontent.com/assets/6780101/16389505/70ad2b9c-3cc8-11e6-8079-b705284881cf.png)
![image](https://cloud.githubusercontent.com/assets/6780101/16389510/7c70099a-3cc8-11e6-9d52-3a86b9d9d846.png)
![image](https://cloud.githubusercontent.com/assets/6780101/16389525/8755596e-3cc8-11e6-82b6-71661d424d6b.png)
