### ISSUE TITLE
Chat screen - Designed layout - Màn hình quản lý việc chat giữa người bán và người mua

### ISSUE THREAD

**Issue by ngchibinh** [reway/bds#92]
![chat](https://cloud.githubusercontent.com/assets/17264625/15770724/08f22232-2990-11e6-9b91-a883729367f0.PNG)

**Comment by tinygipxy** [comment]
- "Lưu trữ" có nghĩa gì nhỉ?
- icon search bên phải trên ý nghĩa gì nhỉ?

**Comment by ngchibinh** [comment]
1.	Vuốt từ phải sang trái để:
a.	Xoá (Màu đỏ)
b.	Lưu trữ (Nút to hơn nút xoá, nằm ngoài cùng, màu xám)
2.	Tên của một thread chat như sau: **5.5 tỷ – Nhà số 12/8 đường Hồ Tùng Mậu** (Hiển thị địa chỉ đến mức đường). Text hiển thị 2 dòng ở màn hình chat inbox. Hiển thị họ và tên người chat.

3.	Tin nhắn chưa đọc sẽ có màu đen đậm

4.	Khi thực hiện việc xoá sẽ phải có confirm. Lưu trữ thì không cần.

**Comment by ngchibinh** [comment]
1.	Screen phần lưu trữ giống phần chat, chỉ loại bỏ các đầu mục: Tất cả, mua, bán/cho thuê

2.	Vuốt từ phải sang trái trong phần lưu trữ để:
a.	Xoá (Màu đỏ)
b.	Thêm(Nút to hơn nút xoá, nằm ngoài cùng, màu xám). Khi click và nút thêm vào sẽ xuất hiện menu “Chuyển về hòm thư chat”
